package dao;

import model.Task;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class TaskDAO {

    private Connection connection;

    public TaskDAO(Connection connection) {
        this.connection = connection;
    }

    // =============================
    // 1. Create Task
    // =============================
    /**
     * Create a new task in the database.
     * 
     * @param task Task object with required data
     * @return true if creation successful, false otherwise
     * 
     * Required fields:
     * - title: Task title (non-empty)
     * - description: Task description (non-empty)
     * - related_type: Type of related entity (customer, lead, deal)
     * - related_id: ID of related entity
     * - assigned_to: User ID to assign task to
     * - priority: Task priority (LOW, MEDIUM, HIGH)
     * - status: Task status (PENDING, IN_PROGRESS, COMPLETED)
     * - due_date: Due date for task completion
     * 
     * Note: task_id is auto-generated by database
     */
    public boolean createTask(Task task) {
        // Validate input
        if (task == null) {
            System.err.println("[TaskDAO] createTask: Task object is null");
            return false;
        }

        if (task.getTitle() == null || task.getTitle().trim().isEmpty()) {
            System.err.println("[TaskDAO] createTask: Title is required");
            return false;
        }

        if (task.getDescription() == null || task.getDescription().trim().isEmpty()) {
            System.err.println("[TaskDAO] createTask: Description is required");
            return false;
        }

        if (task.getDueDate() == null) {
            System.err.println("[TaskDAO] createTask: Due date is required");
            return false;
        }

        String sql = "INSERT INTO Tasks (title, description, related_type, related_id, assigned_to, priority, status, due_date) "
                   + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

        try (PreparedStatement ps = connection.prepareStatement(sql)) {

            ps.setString(1, task.getTitle().trim());
            ps.setString(2, task.getDescription().trim());
            ps.setString(3, task.getRelatedType() != null ? task.getRelatedType() : "");
            ps.setInt(4, task.getRelatedId());
            ps.setInt(5, task.getAssignedTo() > 0 ? task.getAssignedTo() : 0);
            ps.setString(6, task.getPriority() != null ? task.getPriority() : "MEDIUM");
            ps.setString(7, task.getStatus() != null ? task.getStatus() : "PENDING");
            ps.setDate(8, Date.valueOf(task.getDueDate()));

            int rowsAffected = ps.executeUpdate();
            
            if (rowsAffected > 0) {
                System.out.println("[TaskDAO] Task created successfully - Title: " + task.getTitle());
                return true;
            } else {
                System.err.println("[TaskDAO] createTask: Failed to insert task");
                return false;
            }

        } catch (SQLException e) {
            System.err.println("[TaskDAO] createTask: SQL Error - " + e.getMessage());
            e.printStackTrace();
        } catch (Exception e) {
            System.err.println("[TaskDAO] createTask: Error - " + e.getMessage());
            e.printStackTrace();
        }
        return false;
    }

    // =============================
    // 2. Update Task
    // =============================
    /**
     * Update an existing task with new data.
     * 
     * @param task Task object with updated values (task_id must be set)
     * @return true if update successful, false otherwise
     * 
     * Updates fields:
     * - title: Task title (required)
     * - description: Task description (required)
     * - related_type: Type of related entity (customer, lead, deal)
     * - related_id: ID of related entity
     * - priority: Task priority (LOW, MEDIUM, HIGH)
     * - status: Task status (PENDING, IN_PROGRESS, COMPLETED)
     * - due_date: Due date for task completion
     * 
     * Note: Does NOT update assigned_to (use assignTask() for that)
     */
    public boolean updateTask(Task task) {
        // Validate input
        if (task == null) {
            System.err.println("[TaskDAO] updateTask: Task object is null");
            return false;
        }

        if (task.getTaskId() <= 0) {
            System.err.println("[TaskDAO] updateTask: Invalid task ID: " + task.getTaskId());
            return false;
        }

        if (task.getTitle() == null || task.getTitle().trim().isEmpty()) {
            System.err.println("[TaskDAO] updateTask: Title is required");
            return false;
        }

        if (task.getDescription() == null || task.getDescription().trim().isEmpty()) {
            System.err.println("[TaskDAO] updateTask: Description is required");
            return false;
        }

        if (task.getDueDate() == null) {
            System.err.println("[TaskDAO] updateTask: Due date is required");
            return false;
        }

        String sql = "UPDATE Tasks SET title=?, description=?, related_type=?, related_id=?, priority=?, status=?, due_date=? "
                   + "WHERE task_id=?";

        try (PreparedStatement ps = connection.prepareStatement(sql)) {

            ps.setString(1, task.getTitle().trim());
            ps.setString(2, task.getDescription().trim());
            ps.setString(3, task.getRelatedType() != null ? task.getRelatedType() : "");
            ps.setInt(4, task.getRelatedId());
            ps.setString(5, task.getPriority() != null ? task.getPriority() : "MEDIUM");
            ps.setString(6, task.getStatus() != null ? task.getStatus() : "PENDING");
            ps.setDate(7, Date.valueOf(task.getDueDate()));
            ps.setInt(8, task.getTaskId());

            int rowsAffected = ps.executeUpdate();
            
            if (rowsAffected > 0) {
                System.out.println("[TaskDAO] Task updated successfully. Task ID: " + task.getTaskId());
                return true;
            } else {
                System.err.println("[TaskDAO] updateTask: No task found with ID " + task.getTaskId());
                return false;
            }

        } catch (SQLException e) {
            System.err.println("[TaskDAO] updateTask: SQL Error - " + e.getMessage());
            e.printStackTrace();
        } catch (Exception e) {
            System.err.println("[TaskDAO] updateTask: Error - " + e.getMessage());
            e.printStackTrace();
        }
        return false;
    }

    // =============================
    // 3. View Task List
    // =============================
    /**
     * Retrieve all tasks from the database.
     * 
     * @return List of all Task objects; empty list if none found or error occurs
     */
    public List<Task> getAllTasks() {
        List<Task> list = new ArrayList<>();
        String sql = "SELECT * FROM Tasks";

        try (PreparedStatement ps = connection.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                list.add(mapResultSet(rs));
            }

            System.out.println("[TaskDAO] Retrieved " + list.size() + " tasks from database");

        } catch (SQLException e) {
            System.err.println("[TaskDAO] getAllTasks: SQL Error - " + e.getMessage());
            e.printStackTrace();
        } catch (Exception e) {
            System.err.println("[TaskDAO] getAllTasks: Error - " + e.getMessage());
            e.printStackTrace();
        }
        return list;
    }

    // =============================
    // 4. View Task Details
    // =============================
    /**
     * Retrieve a task by its ID from the database.
     * 
     * @param id The unique identifier of the task
     * @return Task object if found, null otherwise
     * 
     * Throws log output if id <= 0
     */
    public Task getTaskById(int id) {
        // Validate input
        if (id <= 0) {
            System.err.println("[TaskDAO] getTaskById: Invalid task ID - " + id);
            return null;
        }

        String sql = "SELECT * FROM Tasks WHERE task_id=?";

        try (PreparedStatement ps = connection.prepareStatement(sql)) {

            ps.setInt(1, id);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                Task task = mapResultSet(rs);
                System.out.println("[TaskDAO] Retrieved task - ID: " + id + ", Title: " + task.getTitle());
                return task;
            } else {
                System.out.println("[TaskDAO] getTaskById: No task found with ID " + id);
                return null;
            }

        } catch (SQLException e) {
            System.err.println("[TaskDAO] getTaskById: SQL Error - " + e.getMessage());
            e.printStackTrace();
        } catch (Exception e) {
            System.err.println("[TaskDAO] getTaskById: Error - " + e.getMessage());
            e.printStackTrace();
        }
        return null;
    }

    // =============================
    // 8. Find tasks by assigned user
    // =============================
    /**
     * Retrieve all tasks assigned to a specific user.
     * 
     * @param userId The ID of the user
     * @return List of tasks assigned to the user; empty list if none found or error occurs
     */
    public List<Task> findByUser(int userId) {
        List<Task> list = new ArrayList<>();
        
        if (userId <= 0) {
            System.err.println("[TaskDAO] findByUser: Invalid user ID - " + userId);
            return list;
        }

        String sql = "SELECT * FROM Tasks WHERE assigned_to = ?";

        try (PreparedStatement ps = connection.prepareStatement(sql)) {
            ps.setInt(1, userId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    list.add(mapResultSet(rs));
                }
            }
            System.out.println("[TaskDAO] Found " + list.size() + " tasks for user ID " + userId);
        } catch (SQLException e) {
            System.err.println("[TaskDAO] findByUser: SQL Error - " + e.getMessage());
            e.printStackTrace();
        } catch (Exception e) {
            System.err.println("[TaskDAO] findByUser: Error - " + e.getMessage());
            e.printStackTrace();
        }
        return list;
    }

    // =============================
    // 5. Assign Task
    // =============================
    /**
     * Assign a task to a specific user.
     * 
     * @param taskId The unique identifier of the task
     * @param userId The ID of the user to assign the task to
     * @return true if assignment successful, false otherwise
     * 
     * Sets status to 'ASSIGNED' when assigning to a user
     */
    public boolean assignTask(int taskId, int userId) {
        // Validate input
        if (taskId <= 0) {
            System.err.println("[TaskDAO] assignTask: Invalid task ID - " + taskId);
            return false;
        }

        if (userId <= 0) {
            System.err.println("[TaskDAO] assignTask: Invalid user ID - " + userId);
            return false;
        }

        String sql = "UPDATE Tasks SET assigned_to=?, status='ASSIGNED' WHERE task_id=?";

        try (PreparedStatement ps = connection.prepareStatement(sql)) {

            ps.setInt(1, userId);
            ps.setInt(2, taskId);

            int rowsAffected = ps.executeUpdate();

            if (rowsAffected > 0) {
                System.out.println("[TaskDAO] Task assigned. Task ID: " + taskId + ", Assigned to User: " + userId);
                return true;
            } else {
                System.out.println("[TaskDAO] assignTask: No task found with ID " + taskId);
                return false;
            }

        } catch (SQLException e) {
            System.err.println("[TaskDAO] assignTask: SQL Error - " + e.getMessage());
            e.printStackTrace();
        } catch (Exception e) {
            System.err.println("[TaskDAO] assignTask: Error - " + e.getMessage());
            e.printStackTrace();
        }
        return false;
    }

    // =============================
    // 6. Track Task Progress (Update Status)
    // =============================
    /**
     * Update the status of an existing task.
     * 
     * @param taskId The unique identifier of the task
     * @param status The new status (PENDING, IN_PROGRESS, COMPLETED, TODO, DONE)
     * @return true if update successful, false otherwise
     * 
     * Valid statuses: PENDING, IN_PROGRESS, COMPLETED, TODO, DONE
     */
    public boolean updateTaskStatus(int taskId, String status) {
        // Validate input
        if (taskId <= 0) {
            System.err.println("[TaskDAO] updateTaskStatus: Invalid task ID - " + taskId);
            return false;
        }

        if (status == null || status.trim().isEmpty()) {
            System.err.println("[TaskDAO] updateTaskStatus: Status is required");
            return false;
        }

        String sql = "UPDATE Tasks SET status=? WHERE task_id=?";

        try (PreparedStatement ps = connection.prepareStatement(sql)) {

            ps.setString(1, status.trim());
            ps.setInt(2, taskId);

            int rowsAffected = ps.executeUpdate();

            if (rowsAffected > 0) {
                System.out.println("[TaskDAO] Task status updated. Task ID: " + taskId + ", Status: " + status);
                return true;
            } else {
                System.out.println("[TaskDAO] updateTaskStatus: No task found with ID " + taskId);
                return false;
            }

        } catch (SQLException e) {
            System.err.println("[TaskDAO] updateTaskStatus: SQL Error - " + e.getMessage());
            e.printStackTrace();
        } catch (Exception e) {
            System.err.println("[TaskDAO] updateTaskStatus: Error - " + e.getMessage());
            e.printStackTrace();
        }
        return false;
    }

    // =============================
    // 8. Update progress percentage
    // =============================
    /**
     * Update task progress percentage and corresponding status.
     * 
     * @param taskId The unique identifier of the task
     * @param progress The progress percentage (0-100)
     * @return true if update successful, false otherwise
     * 
     * Progress mapping:
     * - 0-99%: Status = IN_PROGRESS
     * - 100%: Status = DONE
     */
    public boolean updateProgress(int taskId, int progress) {
        // Validate input
        if (taskId <= 0) {
            System.err.println("[TaskDAO] updateProgress: Invalid task ID - " + taskId);
            return false;
        }

        if (progress < 0 || progress > 100) {
            System.err.println("[TaskDAO] updateProgress: Invalid progress value - " + progress + " (must be 0-100)");
            return false;
        }

        // no dedicated progress column; update status based on progress
        if (progress >= 100) {
            System.out.println("[TaskDAO] updateProgress: Setting task to DONE (100% complete)");
            return updateTaskStatus(taskId, "DONE");
        } else {
            System.out.println("[TaskDAO] updateProgress: Setting task to IN_PROGRESS (" + progress + "%)");
            return updateTaskStatus(taskId, "IN_PROGRESS");
        }
    }

    // =============================
    // 7. Announce Assigned Task (Insert Notification)
    // =============================
    /**
     * Create a notification when a task is assigned to a user.
     * 
     * @param userId The ID of the user being notified
     * @param title The notification title
     * @param content The notification message content
     * @return true if notification created successfully, false otherwise
     */
    public boolean announceAssignedTask(int userId, String title, String content) {
        // Validate input
        if (userId <= 0) {
            System.err.println("[TaskDAO] announceAssignedTask: Invalid user ID - " + userId);
            return false;
        }

        if (title == null || title.trim().isEmpty()) {
            System.err.println("[TaskDAO] announceAssignedTask: Title is required");
            return false;
        }

        if (content == null || content.trim().isEmpty()) {
            System.err.println("[TaskDAO] announceAssignedTask: Content is required");
            return false;
        }

        String sql = "INSERT INTO Notifications (user_id, title, content, type) VALUES (?, ?, ?, 'TASK')";

        try (PreparedStatement ps = connection.prepareStatement(sql)) {

            ps.setInt(1, userId);
            ps.setString(2, title.trim());
            ps.setString(3, content.trim());

            int rowsAffected = ps.executeUpdate();

            if (rowsAffected > 0) {
                System.out.println("[TaskDAO] Notification created. User ID: " + userId + ", Title: " + title);
                return true;
            } else {
                System.err.println("[TaskDAO] announceAssignedTask: Failed to insert notification");
                return false;
            }

        } catch (SQLException e) {
            System.err.println("[TaskDAO] announceAssignedTask: SQL Error - " + e.getMessage());
            e.printStackTrace();
        } catch (Exception e) {
            System.err.println("[TaskDAO] announceAssignedTask: Error - " + e.getMessage());
            e.printStackTrace();
        }
        return false;
    }

    // =============================
    // 9. Delete Task
    // =============================
    /**
     * Delete a task from the database by its ID.
     * 
     * @param taskId The unique identifier of the task to delete
     * @return true if deletion successful, false otherwise
     * 
     * Throws log output if taskId <= 0
     */
    public boolean deleteTask(int taskId) {
        // Validate input
        if (taskId <= 0) {
            System.err.println("[TaskDAO] deleteTask: Invalid task ID - " + taskId);
            return false;
        }

        String sql = "DELETE FROM Tasks WHERE task_id=?";

        try (PreparedStatement ps = connection.prepareStatement(sql)) {

            ps.setInt(1, taskId);
            int rowsAffected = ps.executeUpdate();

            if (rowsAffected > 0) {
                System.out.println("[TaskDAO] Task deleted successfully. Task ID: " + taskId);
                return true;
            } else {
                System.out.println("[TaskDAO] deleteTask: No task found with ID " + taskId);
                return false;
            }

        } catch (SQLException e) {
            System.err.println("[TaskDAO] deleteTask: SQL Error - " + e.getMessage());
            e.printStackTrace();
        } catch (Exception e) {
            System.err.println("[TaskDAO] deleteTask: Error - " + e.getMessage());
            e.printStackTrace();
        }
        return false;
    }

    // =============================
    // Map ResultSet
    // =============================
    private Task mapResultSet(ResultSet rs) throws SQLException {
        Task task = new Task();

        task.setTaskId(rs.getInt("task_id"));
        task.setTitle(rs.getString("title"));
        task.setDescription(rs.getString("description"));
        task.setRelatedType(rs.getString("related_type"));
        task.setRelatedId(rs.getInt("related_id"));
        task.setAssignedTo(rs.getInt("assigned_to"));
        task.setPriority(rs.getString("priority"));
        task.setStatus(rs.getString("status"));

        Date dueDate = rs.getDate("due_date");
        if (dueDate != null) {
            task.setDueDate(dueDate.toLocalDate());
        }

        Timestamp createdAt = rs.getTimestamp("created_at");
        if (createdAt != null) {
            task.setCreatedAt(createdAt.toLocalDateTime());
        }

        // load progress if column exists
        try {
            int prog = rs.getInt("progress");
            if (!rs.wasNull()) {
                task.setProgress(prog);
            }
        } catch (SQLException ignore) {
        }

        return task;
    }
}